language: java
jdk: oraclejdk8

sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build --tag $DOCKER_USERNAME/$APP_NAME .
  - docker tag $DOCKER_USERNAME/$APP_NAME registry.heroku.com/$APP_NAME/web

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push $DOCKER_USERNAME/$APP_NAME;
    docker push registry.heroku.com/$APP_NAME/web;
    heroku container:release web --app $APP_NAME;