spring:
  application.name: products-ws
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/mongodb}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client.serviceUrl.defaultZone: ${EUREKA_URL:http://localhost:7100/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    non-secure-port: ${PUBLIC_PORT:7002}
    secure-port: ${PUBLIC_PORT:7002}

server:
  port: ${PORT:7002}